### ISSUE TITLE
release请求

### ISSUE THREAD

**Issue by Huarch** [Know-Team/NITW_zh-Hans-CN_l10n#4]
可以发布下直接覆盖游戏汉化的补丁吗？

群里目前只有v0.6版本的汉化补丁。萌新卡在图片汉化这步上了😂

**Comment by Sunshine-Planet** [comment]
补丁的制作仍在进行，本储存库目前仅用来记录进度和备份资产。

汉化组会在各项工作完成后在各平台发布汉化补丁正式版并进行 release。

请再等等吧。


若想自己进行图片的替换，图片文件名已携带该图片所对应的 sharedassets 地址和 id，
可以自行使用有关工具（如UABE）进行替换，可以参考视频平台内 Unity 下图片替换的有关教程。
